import 'dart:io';

import 'package:path/path.dart' as p;

import '../models/extracted_string.dart';
import 'base_generator.dart';

/// Generates GetX localization files for a Flutter project.
///
/// **Output structure inside the target project:**
/// ```
/// lib/
///   translations/
///     en_US.dart              ← source locale (values from code, always regenerated)
///     ar_AR.dart              ← other locales (existing translations preserved,
///                                new keys appended as empty placeholders)
///     app_translations.dart   ← GetX Translations subclass
/// ```
class GetxGenerator extends OutputGenerator {
  @override
  Future<void> generate({
    required List<ExtractedString> strings,
    required String projectPath,
    required List<String> locales,
    required String sourceLocale,
  }) async {
    final outputDir = Directory(p.join(projectPath, 'lib', 'translations'))
      ..createSync(recursive: true);

    for (final locale in locales) {
      await _writeLocaleFile(
        outputDir: outputDir,
        locale: locale,
        strings: strings,
        isSourceLocale: locale == sourceLocale,
      );
    }

    await _writeTranslationsClass(outputDir, locales);
    stdout.writeln('[GetX] Written to ${outputDir.path}');
    _printNextSteps(projectPath, locales, sourceLocale);
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  Future<void> _writeLocaleFile({
    required Directory outputDir,
    required String locale,
    required List<ExtractedString> strings,
    required bool isSourceLocale,
  }) async {
    final file = File(p.join(outputDir.path, '$locale.dart'));
    final varName = localeToVarName(locale); // 'en_US' → 'enUS'

    // For non-source locales, read any translations a human already added so
    // they are preserved across CLI runs. New keys get empty placeholders.
    final existing = isSourceLocale ? <String, String>{} : _parseExisting(file);

    final buffer = StringBuffer()
      ..writeln('// Generated by language_extract — do not edit by hand.')
      ..writeln('// Add translations for the "$locale" locale below.')
      ..writeln('// ignore_for_file: prefer_single_quotes')
      ..writeln()
      ..writeln('const Map<String, String> $varName = {');

    for (final s in strings) {
      final String rawValue;
      if (isSourceLocale) {
        // Source locale: use the real extracted value with GetX @param syntax.
        rawValue = s.buildLocaleValue((k) => '@$k');
      } else {
        // Non-source locale: keep existing human translation if present,
        // otherwise fall back to an empty placeholder.
        rawValue = existing[s.key!] ?? '';
      }
      buffer.writeln("  '${s.key}': '${escapeDartString(rawValue)}',");
    }

    buffer.writeln('};');
    await file.writeAsString(buffer.toString());

    final status = isSourceLocale ? 'regenerated' : _mergeStatus(existing, strings);
    stdout.writeln('  ✔ $locale.dart — $status');
  }

  /// Parses an existing GetX locale `.dart` file and returns its key→value map.
  ///
  /// Only reads files previously generated by this tool (known format). Unknown
  /// or corrupted files return an empty map so generation continues safely.
  ///
  /// The values are returned in their **already-escaped Dart form** (e.g.,
  /// `It\'s done`) so they can be written back without double-escaping.
  Map<String, String> _parseExisting(File file) {
    if (!file.existsSync()) return {};
    try {
      final content = file.readAsStringSync();
      final result = <String, String>{};
      // Match 'key': 'value' pairs, tolerating escaped single quotes inside values.
      final pattern = RegExp(r"'((?:[^'\\]|\\.)+)'\s*:\s*'((?:[^'\\]|\\.)*)'");
      for (final m in pattern.allMatches(content)) {
        result[m.group(1)!] = m.group(2)!;
      }
      return result;
    } catch (_) {
      return {};
    }
  }

  /// Prints one-time setup instructions for GetX localization.
  ///
  /// Checks the project's main.dart (and lib/ in general) for existing
  /// `GetMaterialApp` + `AppTranslations` usage so the message is suppressed
  /// on subsequent runs once the app is already wired up.
  void _printNextSteps(
    String projectPath,
    List<String> locales,
    String sourceLocale,
  ) {
    // Search lib/ for any file already referencing AppTranslations — if found,
    // the user has already done the setup so we stay quiet.
    final libDir = Directory(p.join(projectPath, 'lib'));
    if (libDir.existsSync()) {
      final alreadySetUp = libDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.endsWith('.dart'))
          .any((f) {
        final content = f.readAsStringSync();
        return content.contains('AppTranslations') &&
            content.contains('GetMaterialApp');
      });
      if (alreadySetUp) return;
    }

    final sourceParts = sourceLocale.split('_');
    final sourceLang = sourceParts.first;
    final sourceCountry = sourceParts.length > 1 ? sourceParts.last : sourceLang.toUpperCase();

    stdout.writeln('''
┌─────────────────────────────────────────────────────────┐
│  GetX localization one-time setup required              │
├─────────────────────────────────────────────────────────┤
│                                                         │
│  1. Replace MaterialApp with GetMaterialApp in          │
│     main.dart and add translations config:              │
│                                                         │
│     GetMaterialApp(                                     │
│       translations: AppTranslations(),                  │
│       locale: const Locale('$sourceLang', '$sourceCountry'),${' ' * (20 - sourceLang.length - sourceCountry.length)}│
│       fallbackLocale: const Locale('$sourceLang', '$sourceCountry'),${' ' * (12 - sourceLang.length - sourceCountry.length)}│
│       // ... rest of your app config                    │
│     )                                                   │
│                                                         │
│  2. Import the generated translations file:             │
│                                                         │
│     import 'translations/app_translations.dart';        │
│                                                         │
│  3. Use keys anywhere in your app:                      │
│                                                         │
│     Text('my_key'.tr)                                   │
│     Text('greeting'.trParams({'name': userName}))       │
│                                                         │
│  4. Change locale at runtime:                           │
│                                                         │
│     Get.updateLocale(const Locale('ar', 'AR'));         │
└─────────────────────────────────────────────────────────┘''');
  }

  /// Builds a short human-readable status string for the log line.
  String _mergeStatus(Map<String, String> existing, List<ExtractedString> strings) {
    if (existing.isEmpty) return 'created';
    final newKeys = strings.where((s) => !existing.containsKey(s.key)).length;
    return newKeys > 0 ? 'merged (+$newKeys new key(s))' : 'no new keys';
  }

  Future<void> _writeTranslationsClass(
    Directory outputDir,
    List<String> locales,
  ) async {
    final buffer = StringBuffer()
      ..writeln('// Generated by language_extract — do not edit by hand.')
      ..writeln("// Register: GetMaterialApp(translations: AppTranslations())")
      ..writeln();

    for (final locale in locales) {
      buffer.writeln("import '$locale.dart';");
    }

    buffer
      ..writeln()
      ..writeln('// ignore: depend_on_referenced_packages')
      ..writeln("import 'package:get/get.dart';")
      ..writeln()
      ..writeln('class AppTranslations extends Translations {')
      ..writeln('  @override')
      ..writeln('  Map<String, Map<String, String>> get keys => {');

    for (final locale in locales) {
      buffer.writeln("    '$locale': ${localeToVarName(locale)},");
    }

    buffer
      ..writeln('  };')
      ..writeln('}');

    final file = File(p.join(outputDir.path, 'app_translations.dart'));
    await file.writeAsString(buffer.toString());
    stdout.writeln('  ✔ app_translations.dart — regenerated');
  }
}
